In [147]:
import os
import pandas as pd
import numpy as np

### PREPROCESSING STEP

In [148]:
# Define the dataset folder relative to the current notebook folder
folder_path = '..\dataset'  # Relative path to the dataset folder from the notebook folder
file1_path = os.path.join(folder_path, 'SWaT_Dataset_Attack_v0.csv')
file2_path = os.path.join(folder_path, 'SWaT_Dataset_Normal_v0.csv')

# Load the CSV files into dataframes
df1 = pd.read_csv(file1_path)
df2 = pd.read_csv(file2_path)

# Append the two DataFrames
combined_df = df1.append(df2, ignore_index=True)

# Create a separate datetime column for filtering
timestamp_column = ' Timestamp'  
datetime_column = 'Datetime'    
combined_df[datetime_column] = pd.to_datetime(combined_df[timestamp_column], dayfirst=True, errors='coerce')

# Drop rows with invalid Datetime values
combined_df = combined_df.dropna(subset=[datetime_column])

# Sort the DataFrame by the datetime column
combined_df = combined_df.sort_values(by=datetime_column)

# Filter the dataframe for a specific date range
start_date = '2015-12-28 10:00:00' 
end_date = '2015-12-30 12:00:00'
filtered_df = combined_df[(combined_df[datetime_column] >= start_date) & (combined_df[datetime_column] <= end_date)]

# Drop the temporary datetime column before saving (optional)
filtered_df = filtered_df.drop(columns=[datetime_column])

# Save the filtered dataframe to a new CSV in the dataset folder
output_file = os.path.join(folder_path, 'filtered_output.csv')
filtered_df.to_csv(output_file, index=False)

# The dataframe is also available for further processing
print(f"Filtered data saved to: {output_file}")
# print(filtered_df)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17648\3852572746.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_df = df1.append(df2, ignore_index=True)

Filtered data saved to: ..\dataset\filtered_output.csv

In [149]:
# 2. Display the first few rows to get a sense of the data
filtered_df.head()

,Timestamp,FIT101,LIT101,MV101,P101,P102,AIT201,AIT202,AIT203,FIT201,...,P603,Normal/Attack,Timestamp,MV101,AIT201,MV201,P201,P202,P204,MV303
0,28/12/2015 10:00:00 AM,2.427057,522.8467,2.0,2,1,262.0161,8.396437,328.6337,2.445391,...,1,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,28/12/2015 10:00:01 AM,2.446274,522.8860,2.0,2,1,262.0161,8.396437,328.6337,2.445391,...,1,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28/12/2015 10:00:02 AM,2.489191,522.8467,2.0,2,1,262.0161,8.394514,328.6337,2.442316,...,1,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28/12/2015 10:00:03 AM,2.534350,522.9645,2.0,2,1,262.0161,8.394514,328.6337,2.442316,...,1,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,28/12/2015 10:00:04 AM,2.569260,523.4748,2.0,2,1,262.0161,8.394514,328.6337,2.443085,...,1,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
# 3. Summary statistics for numeric columns
filtered_df.describe().T

,count,mean,std,min,25%,50%,75%,max
FIT101,180001.0,1.843634,1.135933,0.000000,0.000000,2.494635,2.587516,2.706659
LIT101,180001.0,595.022355,114.273610,487.951000,509.147500,527.164600,688.571900,925.032300
MV101,180001.0,1.714240,0.464557,0.000000,1.000000,2.000000,2.000000,2.000000
P101,180001.0,1.747429,0.434488,1.000000,1.000000,2.000000,2.000000,2.000000
P102,180001.0,1.002472,0.049660,1.000000,1.000000,1.000000,1.000000,2.000000
AIT201,180001.0,250.479240,13.592720,216.867500,240.323000,258.138900,260.157700,267.719800
AIT202,180001.0,8.422211,0.095444,6.000000,8.381056,8.409895,8.465330,8.581966
AIT203,180001.0,328.909625,5.711614,311.843100,325.070500,331.120200,333.094100,340.169200
FIT201,180001.0,1.831362,1.062380,0.000000,0.081120,2.445263,2.451030,2.804857
MV201,180001.0,1.743907,0.445545,0.000000,1.000000,2.000000,2.000000,2.000000
P201,180001.0,1.031283,0.174082,1.000000,1.000000,1.000000,1.000000,2.000000
P202,180001.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
P203,180001.0,1.743751,0.436562,1.000000,1.000000,2.000000,2.000000,2.000000
P204,180001.0,1.000311,0.017636,1.000000,1.000000,1.000000,1.000000,2.000000
P205,180001.0,1.744857,0.435943,1.000000,1.000000,2.000000,2.000000,2.000000
P206,180001.0,1.000306,0.017477,1.000000,1.000000,1.000000,1.000000,2.000000
DPIT301,180001.0,16.967002,7.172086,0.006402,19.559510,19.822010,19.978870,45.000000
FIT301,180001.0,1.843220,0.810268,0.000000,2.202991,2.208628,2.212215,2.353265
LIT301,180001.0,905.650492,74.004022,580.362700,835.162500,919.195400,967.820800,1200.000000
MV301,180001.0,1.009156,0.131844,0.000000,1.000000,1.000000,1.000000,2.000000
MV302,180001.0,1.806623,0.412775,0.000000,2.000000,2.000000,2.000000,2.000000
MV303,180001.0,1.024928,0.187011,0.000000,1.000000,1.000000,1.000000,2.000000
MV304,180001.0,1.028300,0.206584,0.000000,1.000000,1.000000,1.000000,2.000000
P301,180001.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
P302,180001.0,1.829434,0.376130,1.000000,2.000000,2.000000,2.000000,2.000000
AIT401,180001.0,148.806195,0.003806,148.759900,148.803200,148.808000,148.808000,148.856100
AIT402,180001.0,153.741936,8.009090,146.987900,152.217400,153.345300,154.165600,297.385300
FIT401,180001.0,1.710549,0.103934,0.000000,1.710441,1.717746,1.725179,1.743504
LIT401,180001.0,879.001852,75.508196,572.622400,831.709800,887.157200,932.414800,1002.128000
P401,180001.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
P402,180001.0,1.999972,0.005270,1.000000,2.000000,2.000000,2.000000,2.000000
P403,180001.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
P404,180001.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
UV401,180001.0,1.994278,0.075429,1.000000,2.000000,2.000000,2.000000,2.000000
AIT501,180001.0,7.841924,0.032727,7.782812,7.819662,7.850103,7.855550,8.225006
AIT502,180001.0,144.814001,6.127531,139.374500,143.732400,144.450100,145.167900,272.853100
AIT503,180001.0,264.646231,5.706878,254.293800,260.253800,263.201800,268.072300,291.015100
AIT504,180001.0,13.298080,11.324242,9.536016,12.112280,12.650600,13.419640,255.000000
FIT501,180001.0,1.725151,0.038690,1.206101,1.719559,1.727890,1.735837,1.752628
FIT502,180001.0,1.285270,0.037536,0.801332,1.273985,1.287434,1.301140,1.360318
FIT503,180001.0,0.731819,0.029839,0.333771,0.732068,0.734629,0.735397,0.741542
FIT504,180001.0,0.305460,0.023167,0.000000,0.306569,0.306825,0.308362,0.311693
P501,180001.0,1.994300,0.075283,1.000000,2.000000,2.000000,2.000000,2.000000
P502,180001.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
PIT501,180001.0,249.305044,6.550077,163.884300,248.157500,249.935900,251.265700,253.909300
PIT502,180001.0,1.238438,0.338385,0.000000,0.961138,1.345593,1.537821,1.970333
PIT503,180001.0,188.177676,4.242426,134.468700,187.083400,188.557400,189.694900,191.986000
FIT601,180001.0,0.017546,0.163847,0.000000,0.000000,0.000064,0.000128,1.745363
P601,180001.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
P602,180001.0,1.009589,0.097452,1.000000,1.000000,1.000000,1.000000,2.000000
P603,180001.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
MV101,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AIT201,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MV201,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P201,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P202,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P204,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MV303,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [162]:
# 4. Check for missing values
missing_values = filtered_df.isnull().sum()
print("\nMissing Values in Each Column:\n", missing_values)
filtered_df = filtered_df.dropna(axis=1, how='all')

Missing Values in Each Column:
  Timestamp         0
FIT101             0
LIT101             0
 MV101             0
P101               0
               ...
MV201         180001
P201          180001
P202          180001
P204          180001
MV303         180001
Length: 61, dtype: int64

In [165]:
# 5. Identify columns with single unique value (constant columns)
unique_counts = filtered_df.nunique()
constant_cols = unique_counts[unique_counts == 1].index.tolist()
print("\nColumns with Constant Values:", constant_cols)

Columns with Constant Values: [' P202', 'P301', 'P401', 'P403', 'P404', 'P502', 'P601', 'P603']

In [166]:
# 6. Check for binary columns (columns that only contain 0/1)
# Note: This is a heuristic. Adjust based on domain knowledge.
binary_cols = []
for col in filtered_df.columns:
    unique_vals = filtered_df[col].dropna().unique()
    if sorted(unique_vals) == [0,1]:
        binary_cols.append(col)
print("\nPotential Binary Columns:", binary_cols)

Potential Binary Columns: []

In [167]:
# 7. Check for timestamp and label columns
timestamp_col = 'Timestamp' if ' Timestamp' in filtered_df.columns else None
label_col = 'Normal/Attack' if 'Normal/Attack' in filtered_df.columns else None

print("\nTimestamp Column:", timestamp_col)
print("Label Column:", label_col)

Timestamp Column: Timestamp
Label Column: Normal/Attack

In [133]:
# 8. If needed, separate out the timestamp and label columns
if timestamp_col:
    timestamps = filtered_df[timestamp_col]
    filtered_df = filtered_df.drop(columns=[timestamp_col])

if label_col:
    labels = filtered_df[label_col]
    filtered_df = filtered_df.drop(columns=[label_col])

In [168]:
# 9. Re-check the DataFrame after removing label/timestamp
print("\nDataFrame Shape after removing timestamp/label:", filtered_df.shape)

DataFrame Shape after removing timestamp/label: (180001, 53)

In [171]:
# 10. Check variance to identify low-variance (constant) columns again, if label/timestamp removal changed anything
variance = filtered_df.var(numeric_only=True)
low_variance_cols = variance[variance == 0].index.tolist()
print("\nLow-Variance Columns (Constant after removing label/timestamp):", low_variance_cols)

Low-Variance Columns (Constant after removing label/timestamp): [' P202', 'P301', 'P401', 'P403', 'P404', 'P502', 'P601', 'P603']

In [172]:
# Drop these low-variance columns
if len(low_variance_cols) > 0:
    filtered_df = filtered_df.drop(columns=low_variance_cols)

print("\nDataFrame Shape after dropping low-variance columns:", filtered_df.shape)

DataFrame Shape after dropping low-variance columns: (180001, 45)

In [173]:
# 11. Identify numeric columns (for normalization later)
numeric_cols = filtered_df.select_dtypes(include=[np.number]).columns.tolist()
print("\nNumeric Columns:", numeric_cols)

Numeric Columns: ['FIT101', 'LIT101', ' MV101', 'P101', 'P102', ' AIT201', 'AIT202', 'AIT203', 'FIT201', ' MV201', ' P201', 'P203', ' P204', 'P205', 'P206', 'DPIT301', 'FIT301', 'LIT301', 'MV301', 'MV302', ' MV303', 'MV304', 'P302', 'AIT401', 'AIT402', 'FIT401', 'LIT401', 'P402', 'UV401', 'AIT501', 'AIT502', 'AIT503', 'AIT504', 'FIT501', 'FIT502', 'FIT503', 'FIT504', 'P501', 'PIT501', 'PIT502', 'PIT503', 'FIT601', 'P602']

In [174]:
continuous_cols = [col for col in numeric_cols if col not in binary_cols]
print("\nContinuous Columns (Likely to be Scaled):", continuous_cols)

Continuous Columns (Likely to be Scaled): ['FIT101', 'LIT101', ' MV101', 'P101', 'P102', ' AIT201', 'AIT202', 'AIT203', 'FIT201', ' MV201', ' P201', 'P203', ' P204', 'P205', 'P206', 'DPIT301', 'FIT301', 'LIT301', 'MV301', 'MV302', ' MV303', 'MV304', 'P302', 'AIT401', 'AIT402', 'FIT401', 'LIT401', 'P402', 'UV401', 'AIT501', 'AIT502', 'AIT503', 'AIT504', 'FIT501', 'FIT502', 'FIT503', 'FIT504', 'P501', 'PIT501', 'PIT502', 'PIT503', 'FIT601', 'P602']

In [175]:
# Drop any columns that contain only NaN values
df = filtered_df.dropna(axis=1, how='all')

In [176]:
df.head()

,Timestamp,FIT101,LIT101,MV101,P101,P102,AIT201,AIT202,AIT203,FIT201,...,FIT502,FIT503,FIT504,P501,PIT501,PIT502,PIT503,FIT601,P602,Normal/Attack
0,28/12/2015 10:00:00 AM,2.427057,522.8467,2.0,2,1,262.0161,8.396437,328.6337,2.445391,...,1.279621,0.735269,0.307786,2,250.8652,1.649953,189.5988,0.000128,1,Normal
1,28/12/2015 10:00:01 AM,2.446274,522.8860,2.0,2,1,262.0161,8.396437,328.6337,2.445391,...,1.297554,0.735269,0.307786,2,250.8652,1.649953,189.6789,0.000128,1,Normal
2,28/12/2015 10:00:02 AM,2.489191,522.8467,2.0,2,1,262.0161,8.394514,328.6337,2.442316,...,1.293967,0.735269,0.308619,2,250.8812,1.649953,189.6789,0.000128,1,Normal
3,28/12/2015 10:00:03 AM,2.534350,522.9645,2.0,2,1,262.0161,8.394514,328.6337,2.442316,...,1.281158,0.735269,0.308619,2,250.8812,1.649953,189.6148,0.000128,1,Normal
4,28/12/2015 10:00:04 AM,2.569260,523.4748,2.0,2,1,262.0161,8.394514,328.6337,2.443085,...,1.281158,0.735269,0.308619,2,250.8812,1.649953,189.5027,0.000128,1,Normal

In [ ]:
# Save the filtered dataframe to a new CSV in the dataset folder
preprocess_file = os.path.join(folder_path, 'preprocess_swat.csv')
df.to_csv(preprocess_file, index=False)